[package]
name = "localairouter-daemon"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bytes.workspace = true
chrono.workspace = true
futures.workspace = true
futures-util.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
libc.workspace = true
localairouter-core = { path = "../localairouter-core" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
